#!/usr/bin/perl

use strict;
use warnings;

use DBI;
use File::Copy;
use Image::Magick;
use Cwd 'abs_path';

my $dbfile = $ENV{'FCGI_DATABASE'} or die "env FCGI_DATABASE not set";
my $dbh = DBI->connect("DBI:SQLite:uri=file:$dbfile?mode=rw") or die $DBI::errstr;

#my $sth = $dbh->prepare("CREATE TABLE IF NOT EXISTS gallery(src TEXT, thumbnail TEXT, materiaal TEXT);")
#	or die $dbh->errstr;

#$sth->execute() or die $sth->errstr;

if($ARGV[0] eq "--help" or $ARGV[0] eq "-h") {
	printhelp();
}

if(shift(@ARGV) ne "-m") {
	printhelp();
}

my ($image, $err);
my $rel = "/static/img/gallery/";
my $webroot = $ENV{'FCGI_WEBROOT'} or die "env FCGI_WEBROOT not set";
my $dest = $webroot . $rel;
my $material = shift(@ARGV);
my $sth = $dbh->prepare("INSERT INTO gallery(src, thumbnail, materiaal) VALUES(?, ?, ?);")
	or die $dbh->errstr;

for my $file (@ARGV) {
	my $src = $rel;
	my $thumbnail = $src . "thumb/";
	#TODO create dest if not exists
	copy(abs_path($file), $dest . $file) or die "Failed to copy " .abs_path($file). " to destination $dest$file $!";

	$src .= $file;
	$thumbnail .= $file;

	$image = Image::Magick->new;

	$err = $image->Read($file);
	warn "$err" if "$err";

	$err = $image->Resize('65536@');
	warn "$err" if "$err";

	#$err = $image->Crop('256x256+128+128');
	#warn "$err" if "$err";

	$err = $image->Write($webroot . $thumbnail);
	warn "$err" if "$err";

	$sth->bind_param(1, $src);
	$sth->bind_param(2, $thumbnail);
	$sth->bind_param(3, $material);

	$sth->execute() or die $sth->errstr;

	print "Moved $file to $dest$file\n";
}

sub printhelp {
	print "Usage: $0 -m material FILES...\n";
	exit(1);
}

